apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-stateful-testing
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /TESTE-STORAGE
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop