apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: pod-exposed-2 # select who it's going to listen, the link between the service and the pod
  ports:
    - protocol: TCP
      port: 9000 # port exposed by the service
      targetPort: 80 # port exposed by the pod

# Advantages of using the SVC: it will be more stable than the pod IP, the pod could get killed and recreated, but the service will be stable

# svc-pod-2:9000 > pod-exposed-2:80