apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-testing
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
  volumes:
    - name: cache-volume
      emptyDir:
        sizeLimit: 500Mi