apiVersion: v1
kind: Pod
metadata:
  name: news-db
  labels:
    app: news-db
spec:
  containers:
    - name: db-news-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-config-map