apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: pod-exposed-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000